"""Scaffold utilities.

Generators that turn a config into inputs the pipeline consumes:

- `gen_roi_metadata`        — PRE-staging. Reuses `staging.discover_rois` to list the
  exact ROIs the pipeline will process and writes a template `roi_metadata.csv`
  (an `ROI` column + empty user columns) for the user to fill in.
- `write_signature_template` — writes the phenotyping signature YAML template from a
  marker panel (used by the pre-staging `panel` command). Lists panel markers + example
  cell types for the user to curate before submitting jobs.

`gen_roi_metadata` operates on a single-experiment `Config`; the CLI loops it over a
batch via `config.expand_config`.
"""

from __future__ import annotations

import csv
import logging
from pathlib import Path

from . import staging as staging_stage
from .config import Config
from .utils import ensure_dir, roi_index_from_name

log = logging.getLogger(__name__)


def _roi_sort_key(name: str) -> tuple[int, object]:
    """Sort ROI1, ROI2, ..., ROI10 numerically; push unparseable names to the end."""
    try:
        return (0, roi_index_from_name(name))
    except ValueError:
        return (1, name)


def _roi_output_path(cfg: Config, config_path: Path, output: Path | None) -> Path:
    if output is not None:
        return output
    if cfg.experiment.roi_metadata_csv is not None:
        # Exactly where preprocess._join_roi_metadata reads it.
        return cfg.paths.work_dir / cfg.experiment.roi_metadata_csv
    return config_path.parent / f"roi_metadata_{cfg.experiment.name}.csv"


def gen_roi_metadata(
    cfg: Config,
    *,
    config_path: Path,
    output: Path | None = None,
    extra_columns: list[str] | None = None,
    force: bool = False,
) -> Path | None:
    """Write a template roi_metadata.csv for one experiment.

    Returns the written path, or None if skipped (raw_root unreachable, no ROIs, or
    the destination already exists without --force).
    """
    name = cfg.experiment.name
    try:
        rois = staging_stage.discover_rois(cfg)
    except FileNotFoundError as e:
        log.warning(
            "[bad]raw_root unreachable[/] for [stage]%s[/]: %s — run where RawData is mounted",
            name,
            e,
        )
        return None
    if not rois:
        log.warning(
            "[bad]no ROIs[/] for [stage]%s[/] under [path]%s[/] (glob %s)",
            name,
            cfg.experiment.raw_root,
            cfg.experiment.roi_glob,
        )
        return None

    labels = sorted((p.name for p in rois), key=_roi_sort_key)
    extra = list(extra_columns or [])
    header = ["ROI", *extra]

    dest = _roi_output_path(cfg, config_path, output)
    if dest.exists() and not force:
        log.warning("[warn]exists[/] [path]%s[/] — pass --force to overwrite", dest)
        return None

    ensure_dir(dest.parent)
    # lineterminator="\n": match the repo convention (avoid CRLF; see staging.write_jobs_csv).
    with dest.open("w", newline="") as f:
        w = csv.writer(f, lineterminator="\n")
        w.writerow(header)
        for label in labels:
            w.writerow([label, *([""] * len(extra))])
    log.info(
        "wrote ROI metadata template: [path]%s[/] ([count]%d[/] ROIs)",
        dest,
        len(labels),
    )
    if cfg.experiment.roi_metadata_csv is None and output is None:
        log.info("  set experiment.roi_metadata_csv to [path]%s[/] to have preprocess join it", dest)
    return dest


# Common lineage markers -> (positive, negative, parent). Only cell types with >=1
# positive marker PRESENT in the panel are emitted, as EXAMPLES to edit. Purely a
# scaffold: the user must curate the actual biology.
_COMMON_SIGNATURE: list[tuple[str, list[str], list[str], str]] = [
    ("T cell",        ["CD3", "CD3e", "CD45"],                        ["CD19", "CD68"], "Immune"),
    ("CD4 T cell",    ["CD4"],                                        ["CD8", "CD8a"],  "T cell"),
    ("CD8 T cell",    ["CD8", "CD8a"],                                ["CD4"],          "T cell"),
    ("B cell",        ["CD19", "CD20"],                               ["CD3"],          "Immune"),
    ("NK cell",       ["CD56"],                                       ["CD3"],          "Immune"),
    ("Macrophage",    ["CD68", "CD163"],                              ["CD3"],          "Myeloid"),
    ("Dendritic",     ["CD11c", "HLADR", "HLA-DR"],                   ["CD3"],          "Myeloid"),
    ("Endothelial",   ["CD31", "CD34"],                               ["CD45"],         "Stroma"),
    ("Fibroblast",    ["aSMA", "Vimentin", "PDGFRb"],                 ["CD45"],         "Stroma"),
    ("Epithelial",    ["PanCK", "EpCAM", "CK", "Cytokeratin", "E-cadherin"], ["CD45"],  "Epithelium"),
    ("Proliferating", ["Ki67"],                                       [],               ""),
]


def _render_signature_yaml(name: str, panel: list[str], examples: list[tuple]) -> str:
    lines = [
        f"# Signature-matrix template for '{name}' (generated by the panel command).",
        "# EDIT THIS. The cell types below are GENERIC guesses matched from marker names —",
        "# curate positive/negative markers for YOUR panel + tissue. Names must match the panel.",
        "# scyan builds a table from these; Leiden scores clusters. `parent` builds the coarse label.",
        "#",
        "# Panel markers available:",
    ]
    for i in range(0, len(panel), 8):
        lines.append("#   " + ", ".join(panel[i : i + 8]))
    lines += ["", "version: 1", "", "cell_types:"]
    if not examples:
        lines.append("  # No common lineage markers auto-detected. Define your own, e.g.:")
        lines.append(f"  Cell type A: {{positive: [{panel[0]}], negative: []}}")
    for nm, pos, neg, parent in examples:
        parent_s = f", parent: {parent}" if parent else ""
        lines.append(f"  {nm}: {{positive: [{', '.join(pos)}], negative: [{', '.join(neg)}]{parent_s}}}")
    return "\n".join(lines) + "\n"


def write_signature_template(
    name: str,
    markers: list[str],
    dest: Path,
    *,
    force: bool = False,
) -> Path | None:
    """Write a phenotyping signature-matrix YAML template from a marker panel.

    Lists every panel marker (as a reference comment) and pre-fills example cell types
    built from markers present in the panel, for the user to curate. Skips (returns None,
    logs) when `dest` already exists and `force` is False, so curated edits are never
    clobbered. Returns the written path.
    """
    if not markers:
        log.warning("[bad]empty marker panel[/] — no signature template written")
        return None
    if dest.exists() and not force:
        log.warning("[warn]exists[/] [path]%s[/] — pass --force to regenerate", dest)
        return None

    present = set(markers)
    examples = []
    for nm, pos, neg, parent in _COMMON_SIGNATURE:
        pos_p = [m for m in pos if m in present]
        if not pos_p:
            continue
        examples.append((nm, pos_p, [m for m in neg if m in present], parent))

    ensure_dir(dest.parent)
    dest.write_text(_render_signature_yaml(name, markers, examples))
    log.info(
        "wrote signature template: [path]%s[/] ([count]%d[/] panel markers, [count]%d[/] example types)",
        dest,
        len(markers),
        len(examples),
    )
    log.info("  edit it, then set [stage]phenotype.signature_matrix[/] to this path")
    return dest
